### ISSUE TITLE
为什么系统自带的 App 似乎不能替换图标

### ISSUE THREAD

**Issue by MassenEvan** [underthestars-zhy/IconChanger#1]
其他的 app 都可以，但试了几个系统自带的 app 都不能替换，比如 safari

**Comment by underthestars-zhy** [comment]
会在下一个版本修复这个问题

**Comment by underthestars-zhy** [comment]
估计修复不了了。系统自带的App具有SIP保护，你可以尝试关闭SIP后更换图标。
https://www.reddit.com/r/MacOS/comments/kzzrub/tut_how_to_change_any_system_folder_finder_icon/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by underthestars-zhy** [comment]
不过在后续版本会考虑使用通过创建一个桥接App来解决这个问题

**Comment by MassenEvan** [comment]
> 不过在后续版本会考虑使用通过创建一个桥接App来解决这个问题

谢谢！App 很棒！

**Comment by underthestars-zhy** [comment]
> 问一下为什么api谷歌好像比microsoft/edge快一点

IconChanger获取图标的Api与浏览器无关，如果你遇到了速度相关的问题请打开一个新的issue
