### ISSUE TITLE
[BUG] Icon 列表中出现未知空行

### ISSUE THREAD

**Issue by EstrellaXD** [underthestars-zhy/IconChanger#12]
System: macOS 13.1 (22C65)
Version: 1.2.5 (14)

问题描述：本应该连续的 App icon 列表出现了空行，更改软件的 Window size 也依旧存在

问题截图：
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/33726646/208673590-0990cc8b-2281-4b59-b38b-179546a0ab3a.png">

**Comment by underthestars-zhy** [comment]
This is a duplicated issue. Please look at #10
