### ISSUE TITLE
从Launchpad里隐藏图标之后整个Launchpad里的图标顺序会被打乱

### ISSUE THREAD

**Issue by andykeppel** [underthestars-zhy/IconChanger#15]
设备信息：MacBook Air Retina, 13-inch, 2020，macOS 13.1 (22C65)

而且所有的文件夹都空了：
<img width="1440" alt="截屏2022-12-22 00 54 09" src="https://user-images.githubusercontent.com/62137704/208961000-23cac5d3-c8ef-45fd-9a80-dda25d998e4e.png">

**Comment by underthestars-zhy** [comment]
重复Issue #13
