### ISSUE TITLE
打开崩溃问题

### ISSUE THREAD

**Issue by wyg-lucas** [underthestars-zhy/IconChanger#16]
M1 pro Ventura 13.1系统
打开软件提示崩溃，然后重新打开显示找不到该软件

**Comment by underthestars-zhy** [comment]
请问你将App拖动到Application文件夹了吗Sent from my iPhoneOn Dec 22, 2022, at 01:11, wyg_lucas ***@***.***> wrote:﻿
M1 pro Ventura 13.1系统
打开软件提示崩溃，然后重新打开显示找不到该软件

**Comment by underthestars-zhy** [comment]
#9 这里面的解决办法试一下

**Comment by underthestars-zhy** [comment]
如果仍然有问题，请在此告知
