### ISSUE TITLE
社区版图标无法搜索

### ISSUE THREAD

**Issue by mybdye** [underthestars-zhy/IconChanger#17]
<img width="240" alt="图片" src="https://user-images.githubusercontent.com/21116709/209045776-e9d288b2-2b8b-4b48-a3fa-fcb0f596eae0.png">

<img width="240" alt="图片" src="https://user-images.githubusercontent.com/21116709/209045360-ab77b6d4-8286-48ae-af71-2475adad4d20.png">

<img width="500" alt="图片" src="https://user-images.githubusercontent.com/21116709/209045447-ae700768-34c9-4e31-a409-2079cd5baf92.png">
<img width="500" alt="图片" src="https://user-images.githubusercontent.com/21116709/209045603-9a6ec06f-a077-4f4c-9fc3-c5f93550ad67.png">
<img width="500" alt="图片" src="https://user-images.githubusercontent.com/21116709/209046021-36f00ad9-61ef-4c18-9e8f-8a1fb3843097.png">

**Comment by underthestars-zhy** [comment]
请设置别名为Pycharm

**Comment by underthestars-zhy** [comment]
https://github.com/underthestars-zhy/IconChanger#if-iconchanger-doenst-show-any-icon-for-certain-app

**Comment by underthestars-zhy** [comment]
如果仍然有问题，请在此告知
