### ISSUE TITLE
[bug report] 找不到 wechatwebdevtools 的图标

### ISSUE THREAD

**Issue by jissin** [underthestars-zhy/IconChanger#2]
使用关键词 「wechat dev」可以在网站上搜索到，是否考虑在应用内添加关键词输入框，否则一些特殊命名的应用无法找到图标

**Comment by underthestars-zhy** [comment]
在下一个版本会解决，会可以设置搜索别名

**Comment by underthestars-zhy** [comment]
![CleanShot 2022-06-27 at 14 03 39@2x](https://user-images.githubusercontent.com/46642225/175870246-454db9ed-418f-4f33-b0d7-0556e4ad1dda.png)
![CleanShot 2022-06-27 at 14 03 47@2x](https://user-images.githubusercontent.com/46642225/175870248-568b9048-e824-43bd-bb50-ee9d439d6e38.png)
<img width="263" alt="CleanShot 2022-06-27 at 14 04 07@2x" src="https://user-images.githubusercontent.com/46642225/175870296-e0348b69-feba-4a06-8b09-eec0e225c982.png">

**Comment by underthestars-zhy** [comment]
https://github.com/underthestars-zhy/IconChanger/releases/tag/v1.1.4
