### ISSUE TITLE
能否支持修改JetBrains Toolbox安装的程序图标

### ISSUE THREAD

**Issue by jiangshengdev** [underthestars-zhy/IconChanger#23]
使用JetBrains Toolbox安装程序后，会有2份app文件，

一份是在

~/Applications/JetBrains Toolbox/WebStorm.app

而另外一份则在

~/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/223.8214.51

目前仅支持

~/Applications/JetBrains Toolbox

下的图标修改，能否修改此文件后，自动修改

~/Library/Application Support/JetBrains/Toolbox/apps

下的图标

**Comment by tzm41** [comment]
2023.1版本会更新图标了：https://youtrack.jetbrains.com/issue/IDEA-256202。

**Comment by jiangshengdev** [comment]
> 2023.1版本会更新图标了：https://youtrack.jetbrains.com/issue/IDEA-256202

已经2年了，终于要更新图标了吗。希望官方图标比我的好看

https://macosicons.com/#/u/twilightwalker
