### ISSUE TITLE
每次软件更新后可以自动替换图标吗

### ISSUE THREAD

**Issue by tzm41** [underthestars-zhy/IconChanger#28]

**Comment by tzm41** [comment]
像Notion这样时不时更新，图标选择又很多的app，希望可以有自动替换的功能。如果无法实现，至少可以记住之前选择的图标然后一键替换？

**Comment by underthestars-zhy** [comment]
会在1.3支持

**Comment by tzm41** [comment]
1.3什么时候会发布呢

**Comment by SheepAndWolf** [comment]
> 在2月份末Sent from my iPhoneOn Jan 24, 2023, at 15:33, Colin Tan ***@***.***> wrote:﻿ 1.3什么时候会发布呢 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

等待中。。。

**Comment by tzm41** [comment]
等待中……

**Comment by underthestars-zhy** [comment]
可能要晚一点，被一个问题卡住了Sent from my iPhoneOn Mar 21, 2023, at 13:16, Colin Tan ***@***.***> wrote:﻿
等待中……

**Comment by HowieHye** [comment]
可以暂时这样解决，在`/Applications/IconChanger.app/Contents/Resources/helper.sh`文件末尾添加`killall Dock`，然后打开`IconChanger`，`Install Helper Again`。
<img width="518" alt="image" src="https://github.com/underthestars-zhy/IconChanger/assets/36627364/36616400-4b7b-47ef-8160-1c48cdbcaa56">

**Comment by tzm41** [comment]
现在进度如何了

**Comment by underthestars-zhy** [comment]
WWDC后一周左右做完

**Comment by tzm41** [comment]
👀

**Comment by KenWuqianghao** [comment]
等待中……

**Comment by tzm41** [comment]
重构的进度如何了？

**Comment by KenWuqianghao** [comment]
感觉寄了，上次commit是去年了

**Comment by tzm41** [comment]
作者6月份评论说“我们现在正在Apple工程师的帮助下对App进行全部的重构”，我还是在期待着……不知道TA在和我司哪个组合作呢

**Comment by jqtmviyu** [comment]
`pictogramapp` 这个内测试期免费的软件说它能实现, 但没有经过测试

**Comment by tzm41** [comment]
Looks like the author had abandoned the project. Closing the issue.
