### ISSUE TITLE
[bug] [feature] 使用中发现的一些问题以及建议

### ISSUE THREAD

**Issue by 5mdld** [underthestars-zhy/IconChanger#3]
谢谢开发者，很好用的app，终于不用手动换图标了，不过使用中还是发现了一些小问题，望改进

~~1. 暗色模式下主界面的图标边缘有锯齿（图1）
<img width="101" alt="image" src="https://user-images.githubusercontent.com/88809953/175820144-ceffbb72-d645-4ee3-8748-be48879e0f77.png">~~

~~2. 每次切换图标都要输入电脑密码（不能调用touch id，不清楚是系统机制还是bug）~~

~~3. 偏好设置中Query Host默认为空，但是更改后再留空的话，搜索功能就会失效，必须重新填入“p1txh7zfb3-3.algolianet.com”等之后才能继续使用~~

~~4. 主界面app名称的排版有点怪（图2）
<img width="628" alt="image" src="https://user-images.githubusercontent.com/88809953/175820397-91f3d8d2-5711-4c93-a6b1-876104638d6c.png">~~

~~5. 主界面鼠标滚动有点不流畅~~

6. 希望之后版本能增加图标批量切换（可以锚定网站上评分最高的图标作为默认值）和自动切换功能，有些app更新后图标会变回去

7. 希望能提交到homebrew，谢谢！

**Comment by underthestars-zhy** [comment]
锯齿问题和滚动问题在新版本修复了，不过不确定在macOS12上的表现
https://github.com/underthestars-zhy/IconChanger/releases/tag/v1.1.4

**Comment by 5mdld** [comment]
（macOS 12.4）谢谢，图标边缘锯齿问题已解决，不过主界面预览的图标模糊（如图）
![image](https://user-images.githubusercontent.com/88809953/175875457-812a69c8-389b-414a-9286-a401f84b0042.png)

另外滚动依然不太流畅，开启第三方的平滑滚动插件后有所好转

**Comment by underthestars-zhy** [comment]
> （macOS 12.4）谢谢，图标边缘锯齿问题已解决，不过主界面预览的图标模糊（如图）
> 
> ![image](https://user-images.githubusercontent.com/88809953/175875457-812a69c8-389b-414a-9286-a401f84b0042.png)
> 
> 
> 
> 另外滚动依然不太流畅，开启第三方的平滑滚动插件后有所好转

请问你的系统版本是什么

**Comment by underthestars-zhy** [comment]
![CleanShot 2022-06-27 at 15 35 04@2x](https://user-images.githubusercontent.com/46642225/175885188-8828618b-0ee0-442e-b7b1-c5e39cc88065.png)
在macOS13上是清晰的，估计是系统问题，如果在9月份升级macOS13后还是有问题请告知

**Comment by underthestars-zhy** [comment]
> 主界面app名称的排版有点怪（图2）

暂时没有比较好的解决办法，因为这种是没有空格的名称，不过可以尝试拉大window解决。
![CleanShot 2022-06-27 at 15 46 50@2x](https://user-images.githubusercontent.com/46642225/175887638-cc0ff660-7d64-4f18-879d-ecfca313105d.png)

**Comment by underthestars-zhy** [comment]
Query Host的问题已经解决了，在下个版本会推出

**Comment by underthestars-zhy** [comment]
Query host and problem of password has fixed.
See: https://github.com/underthestars-zhy/IconChanger/releases/tag/v1.2.0

**Comment by 5mdld** [comment]
谢谢作者更新，发现全屏状态下排版有问题
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/88809953/176134507-0be7b55c-4844-4c87-b93a-11112203dc44.png">

**Comment by underthestars-zhy** [comment]
在macOS13的时候会自动修复，似乎是SwiftUI的问题

**Comment by underthestars-zhy** [comment]
图标问题解决了，homebrew暂时没有意向。
