### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ethanz-code** [underthestars-zhy/IconChanger#37]
建议开发者多找找Icon这类后端接口，或者优化逻辑，因为有些app它使用人数很少，但又想快速替换一些比较好看的icon，另外还有app全称拿过去如果直接请求后端接口传入详细app名称参数可能就会找不到icon，可以模糊搜索一下，然后从显示icon数量这块做些限制

**Comment by coder-zhangsir** [comment]
目前Mac13.4.1版本功能使用正常
