### ISSUE TITLE
无法载入图标

### ISSUE THREAD

**Issue by tanmx** [underthestars-zhy/IconChanger#4]
已经配置了磁盘权限以及host,软件还是空白
**关闭软件后重新打开，host 的配置又没了**
OS：MacOS 12.4 (21F79)

<img width="752" alt="image" src="https://user-images.githubusercontent.com/3370587/176803297-79cd31e9-20a6-4c99-8896-ba8eef8f29cf.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/3370587/176803634-b045e7be-f52e-420d-bf93-74bb7d3f2c36.png">

**Comment by underthestars-zhy** [comment]
在1.2.1也是这样吗

**Comment by tanmx** [comment]
> 在1.2.0也是这样吗

1.1.4和1.2.0都是一样的情况，是不是macos 12系统不能用

**Comment by underthestars-zhy** [comment]
之前在旅游，所以没法处理。

`echo /private$(getconf DARWIN_USER_DIR)com.apple.dock.launchpad/db/db` 

在终端运行以下代码，输出什么

**Comment by underthestars-zhy** [comment]
host的配置在没有的情况下应该是可以继续使用的

**Comment by tanmx** [comment]
> echo /private$(getconf DARWIN_USER_DIR)com.apple.dock.launchpad/db/db

```
> echo /private$(getconf DARWIN_USER_DIR)com.apple.dock.launchpad/db/db
/private/var/folders/mm/j0xl2xdj3ld718y1_3w4pmn40000gn/0/com.apple.dock.launchpad/db/db
```

**Comment by underthestars-zhy** [comment]
是否可以通过Finder访问这个path，然后找到一个叫`db`的文件。如果有麻烦上传一下

**Comment by tanmx** [comment]
> 是否可以通过Finder访问这个path，然后找到一个叫`db`的文件。如果有麻烦上传一下


https://cdn.jsdelivr.net/gh/tanmx/pic@main/2022/07/db.jpg   下载后重命名去除后缀

**Comment by tanmx** [comment]
升级13 然后TM 降级 12.4 后 正常使用了，原因不明

**Comment by kevin-onepiece** [comment]
我也是同样的情况
<img width="750" alt="image" src="https://user-images.githubusercontent.com/36980899/192088999-b1410191-35a3-4459-bbd9-ca3fd8d0350b.png">
[db.zip](https://github.com/underthestars-zhy/IconChanger/files/9638271/db.zip)
