### ISSUE TITLE
[bug] App闪退 & Mac App Store下载的应用不能更换图标

### ISSUE THREAD

**Issue by 5mdld** [underthestars-zhy/IconChanger#5]
系统：macOS 12.4
App版本：1.2.0
App在使用时间歇性崩溃，不能稳定复现，但是今天已经崩溃三次了，附崩溃信息
另外Mac App Store下载的应用不能更换图标
[crash.txt](https://github.com/underthestars-zhy/IconChanger/files/9036312/crash.txt)

**Comment by underthestars-zhy** [comment]
Mac App Store无法更换的问题已经解决。崩溃由于SwiftUI暂时看不出原因，不过大概率是Apple的问题，在macOS13下没有出现
