### ISSUE TITLE
载入 APP 列表不正常，APP 忽闪忽现

### ISSUE THREAD

**Issue by zhdsmy** [underthestars-zhy/IconChanger#6]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/8348149/178983966-bce1c74f-99c4-4504-8c9c-519ebe50de33.png">

版本 1.2.2(11)

另外能不能支持从本地磁盘选择 icns 文件

**Comment by underthestars-zhy** [comment]
请问你的系统版本是？

**Comment by underthestars-zhy** [comment]
本地文件选择已经支持
